### ISSUE TITLE
Implement exceptions

### ISSUE THREAD

**Issue by plesubc** [peatrc/bc_terrain_parser#1]
If a terrain string is somehow invalid, it should raise an Exception of some sort to let the end user know there is something wrong. 

Here is a very simple example of exception handling, which will trigger if you create an instance of Example and don't pass the string "a" as a parameter.

```
class FailError(Exception):
    pass

class Example:
    def __init__(self, whatever:str):
        self.whatever = whatever
        if self.whatever != 'a':
            raise FailError(f'whatever="{self.whatever}" is not valid')

if __name__ == '__main__':
    try:
        i_tried = Example('a') #this doesn't generate an exception
        i_tried = Example('b')#but this does
    except FailError as err:
        print(type(err))
        print(err.args)
        print(err)
        print(f'and here I use this value of {i_tried.whatever}') # you know this because of the error message
        raise #if you want to raise the error too.

```

---

The output looks like this if you run a file containing this code:
```
('whatever="b" is not valid',)
whatever="b" is not valid
and here I use this value of a
Traceback (most recent call last):
  File "/Users/paul/tmp/Error.py", line 14, in <module>
    i_tried = Example('b')
              ^^^^^^^^^^^^
  File "/Users/paul/tmp/Error.py", line 9, in __init__
    raise FailError(f'whatever="{self.whatever}" is not valid')
FailError: whatever="b" is not valid
```

**Comment by peatrc** [comment]
Lines 595-601 implement something like this.  I have it so the script raises a ValueError message listing all the parts of the string that were unparsed.  I also introduced a variable called strictmode, so if strictmode==1 then the script only returns the exception, but if strictmode ==0 it will raise the exception but also return the rest of the parsed object that was presumed to be parsed correctly.

**Comment by peatrc** [comment]
The lines look like this:
--------------------------
            #return as normal if there is no record of unparsed terms in new_list[i][6]
            if new_list[i][6] == '':
                return(new_list)
            else: # goes here if there were unparsed items, treated differently whether it is in strict mode or not
                raise ValueError(new_list[i][6])

        except ValueError as e:
            print('Exception Raised from unparsed terms from input: ', e)
            if strictmode == 0:
                return(new_list)

**Comment by plesubc** [comment]
That code doesn't raise a ValueError regardless of the strictmode parameter.

1. strictmode should be `True` or `1` to enable strictmode
2. If strictmode is `True`, then the exception should be raised and the message will give details, but the handling of the exception is left outside of your package.
3. If strictmode is `False`, you can return the list. You may want to have a look at the `logging` standard library as well.


if you want to raise a ValueError:

```
if strictmode == 1:
	raise ValueError(new_list[i][6])) # Or whatever you want as the message
else:
	return(new_list)
```

You don't need the `try` and `except` because that block will be created if necessary in the code that uses `import bctcs`.

**Comment by plesubc** [comment]
You may also want to have a look at <https://docs.python.org/3/library/traceback.html>

**Comment by peatrc** [comment]
> That code doesn't raise a ValueError regardless of the strictmode parameter.
> 
> 1. strictmode should be `True` or `1` to enable strictmode
> 2. If strictmode is `True`, then the exception should be raised and the message will give details, but the handling of the exception is left outside of your package.
> 3. If strictmode is `False`, you can return the list. You may want to have a look at the `logging` standard library as well.
> 
> if you want to raise a ValueError:
> 
> ```
> if strictmode == 1:
> 	raise ValueError(new_list[i][6])) # Or whatever you want as the message
> else:
> 	return(new_list)
> ```
> 
> You don't need the `try` and `except` because that block will be created if necessary in the code that uses `import bctcs`.

Sorry I'm not so clear on everything here.

So you think I should remove the try and except sections and just replace it with that simple conditional checking in strictmode==¡ (which will determine whether to the newlist as usual or raise an exception?

Now I'm not sure if ValueError is the most appropriate built-in exception... but I think it works?  Fundamentally the issue that it's reporting is that the value that's trying to be parsed does not exist in an appropriate dictionary... so either it's the wrong Value, or the person who inputted the code put the right value in the wrong logical order in the code so its looking in the wrong dictionary... but that is more of a "CodeLogic/Syntax" error... idk if there's a simple way to tell the difference, and I think it will take a large amount of work to try and re-interpret terrain codes by trying to figure out if characters were put in the wrong order -- when speaking in english with a non-native speaker it seems easy enough to unscramble the order or their words to make best sense of what they're trying to say, but for this parser I think it means going through a ton or permutations and guessing which permutation is the best guess, and that seems like a big undertaking now lol.

**Comment by peatrc** [comment]
Oh... or did you mean the try and except are going to still occur, but instead it will be inside the other script that's calling on BCTCS?

**Comment by plesubc** [comment]
> Oh... or did you mean the try and except are going to still occur, but instead it will be inside the other script that's calling on BCTCS?

Yes. The user of the bctcs module is the one that handles the exception which should be raised if the object is created with `strictmode=True`.

You can very easily create your own exceptions by subclassing `Exception`.  So if you don't want to use ValueError you can use:
```
class BCTCSError(Exception):
   pass
```

**Comment by peatrc** [comment]
So to be clear, simply raising an exception inside of BCTCS will return that back into the loading script... I don't have to do an explicit return statement?  How does the loading script access the ValueError?  

(And yes, I think the ValueError should simply be the value of new_list[i][6] -- basically I've been writing it assuming that that value is recording all the unparsed characters as it goes through the whole code, so it's ready to spit out its results once it's reached the end)

**Comment by plesubc** [comment]
If your software raises an exception, that's propagated down the line. For example, if you use `requests`

```
import requests
requests.get('adfjldasfjl;dsfhjkasdff')
```

This will produce:
```
requests.exceptions.MissingSchema: Invalid URL 'adkf': No scheme supplied. Perhaps you meant https://adkf?
```

But if I did:
```
import requests

try:
    requests.get('adfjldasfjl;dsfhjkasdff')
except requests.exceptions.MissingSchema:
    print('Success!')
```

I would get the output of `Success!`. And if I wanted extra details I would use `traceback` and `sys`.

**Comment by peatrc** [comment]
OK I think I've almost got it, but I was expecting it to print the exception but then go back to processing the rest of the codes in the try loop, but instead it stopped and printed the ValueError.  Is this the behaviour that we want?

**Comment by peatrc** [comment]
On another note... The error that it stopped at isn't in the dictionary, but I think there's an intepretation of this error that is in fact not an error, but I need to go adjust the main algorithm... there's an issue where Terrain Types have a default of Active or Inactive states (or not applicable for some), but if you state Active or Inactive in a code it's supposed to specify the opposite of the default (or throw an Error if it tries to specify I or A for one where it's N/A)... I think it might be as easy as needing to hardcode the default active/inactive states for each terrain type in the appropriate dictionary, and if the A or I pops up in the code then I can just check against the default and specify the opposite in the parsed output.   

Should we make this another "issue" in git?

**Comment by plesubc** [comment]
> OK I think I've almost got it, but I was expecting it to print the exception but then go back to processing the rest of the codes in the try loop, but instead it stopped and printed the ValueError. Is this the behaviour that we want?

The exception is intended to cause the program to crash. The message that goes with the exception states *why*. That way, the programmer can see what happened and continue the program or not, as is required.

**Comment by plesubc** [comment]
there's an issue where Terrain Types have a default of Active or Inactive states (or not applicable for some), but if you state Active or Inactive in a code it's supposed to specify the opposite of the default (or throw an Error if it tries to specify I or A for one where it's N/A)... I think it might be as easy as needing to hardcode the default active/inactive states for each terrain type in the appropriate dictionary, and if the A or I pops up in the code then I can just check against the default and specify the opposite in the parsed output.
> 
> Should we make this another "issue" in git?

It wouldn't hurt; you should consider using issues as bug trackers so that you know what is fixed and what is not.

Also, if there are 3 states, (active, inactive, not applicable), then a boolean may not be the most appropriate. Even if you have True, False and None, None still evaluates to False. So you may be left with no alternative but active, inactive and N/A.

**Comment by peatrc** [comment]
I just started a new issue.  Gonna think about the best approach first.  My first hunch is just define the default state right in the dictionary values, then if the parser encounters a A/I just modify the output string accordingly.  E.g., parser will automatically include Active or Inactive or N/A in its output, but if it encounters an A or I it will 1) reject it if an N/A is present in the default, or 2) remove the default Active/Inactive and replace it with whatever is specified Active/Inactive.  I think it could be that simple?

**Comment by peatrc** [comment]
Is this issue now resolved?

**Comment by plesubc** [comment]
If the code as pushed to Github meets all the criteria as discussed above, then yes, this issue is closed. You can put a link to the commit which implements the changes into the comment. ie "Close with comment".

**Comment by peatrc** [comment]
Implemented with the following commits:
vscode://eamodio.gitlens/link/r/da2b7815b78a91d755c3b1df7f23edc8af5c2eff/c/5539dd3e4ec1b431e717f8bdb93c422fede1ba44?url=https%3A%2F%2Fgithub.com%2Fpeatrc%2Fbc_terrain_parser.git
vscode://eamodio.gitlens/link/r/da2b7815b78a91d755c3b1df7f23edc8af5c2eff/c/54b56893502b356dfaf52263fbb81c8f858ab56a?url=https%3A%2F%2Fgithub.com%2Fpeatrc%2Fbc_terrain_parser.git

**Comment by peatrc** [comment]
https://github.com/peatrc/bc_terrain_parser/commit/5539dd3e4ec1b431e717f8bdb93c422fede1ba44

https://github.com/peatrc/bc_terrain_parser/commit/5539dd3e4ec1b431e717f8bdb93c422fede1ba44
